import { Link } from 'react-router-dom'
import axios from 'axios'
import { authApi } from '@/services/api'
import jsPDF from 'jspdf'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import {
    Zap,
    Briefcase,
    BarChart3,
    FileText,
    Settings,
    LogOut,
    Mail,
    Sparkles,
    Download,
    Copy,
    RefreshCw,
    Building2,
    Menu,
    X,
    Check,
    Wand2,
    PenTool,
} from 'lucide-react'
import { useState } from 'react'
import { useAuthStore } from '@/store'
import type { User } from '@/lib/types'

const toneOptions = [
    { id: 'formal', label: 'Formal', description: 'Professional and traditional', icon: '👔' },
    { id: 'casual', label: 'Casual', description: 'Friendly and approachable', icon: '😊' },
    { id: 'startup', label: 'Startup', description: 'Innovative and energetic', icon: '🚀' },
    { id: 'corporate', label: 'Corporate', description: 'Polished and executive', icon: '🏢' },
]

export default function CoverLetterPage() {
    const { user, logout } = useAuthStore()
    const [sidebarOpen, setSidebarOpen] = useState(false)
    const [step, setStep] = useState<'input' | 'generating' | 'result'>('input')
    const [selectedTone, setSelectedTone] = useState('formal')
    const [companyName, setCompanyName] = useState('')
    const [roleName, setRoleName] = useState('')
    const [jobDescription, setJobDescription] = useState('')
    const [generatedLetter, setGeneratedLetter] = useState('')
    const [copied, setCopied] = useState(false)

    const navItems = [
        { icon: Briefcase, label: 'Applications', href: '/dashboard' },
        { icon: BarChart3, label: 'Analytics', href: '/analytics' },
        { icon: FileText, label: 'Resumes', href: '/resumes' },
        { icon: PenTool, label: 'Cover Letters', href: '/cover-letters', active: true },
        { icon: Settings, label: 'Settings', href: '/settings' },
    ]

    const handleGenerate = async () => {
        setStep('generating')

        try {
            const response = await axios.post('/api/cover-letters/generate', {
                company: companyName,
                role: roleName,
                jobDescription,
                tone: selectedTone.toUpperCase(),
            })

            if (response.data.success) {
                setGeneratedLetter(response.data.data.content)
                setStep('result')
            }
        } catch (error) {
            console.error('Failed to generate cover letter:', error)
            setStep('input')
        }
    }

    const handleCopy = () => {
        navigator.clipboard.writeText(generatedLetter)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    const handleDownloadPDF = () => {
        try {
            const pdf = new jsPDF('p', 'mm', 'a4')
            const pageWidth = pdf.internal.pageSize.getWidth()
            const pageHeight = pdf.internal.pageSize.getHeight()
            const margin = 20
            const maxWidth = pageWidth - margin * 2

            // Add title
            pdf.setFontSize(16)
            pdf.setFont('helvetica', 'bold')
            pdf.text(`Cover Letter - ${companyName}`, margin, margin + 10)

            // Add role
            pdf.setFontSize(12)
            pdf.setFont('helvetica', 'italic')
            pdf.text(`Position: ${roleName}`, margin, margin + 18)

            // Add separator line
            pdf.setDrawColor(200)
            pdf.line(margin, margin + 24, pageWidth - margin, margin + 24)

            // Add cover letter content
            pdf.setFontSize(11)
            pdf.setFont('times', 'normal')

            const lines = pdf.splitTextToSize(generatedLetter, maxWidth)
            let yPosition = margin + 35

            for (const line of lines) {
                if (yPosition > pageHeight - margin) {
                    pdf.addPage()
                    yPosition = margin
                }
                pdf.text(line, margin, yPosition)
                yPosition += 6
            }

            // Add footer
            pdf.setFontSize(8)
            pdf.setTextColor(150)
            pdf.text('Generated by ApplyOps', margin, pageHeight - 10)
            pdf.text(new Date().toLocaleDateString(), pageWidth - margin - 20, pageHeight - 10)

            pdf.save(`cover_letter_${companyName.toLowerCase().replace(/\s+/g, '_') || 'generated'}.pdf`)
        } catch (error) {
            console.error('PDF generation failed:', error)
            alert('Failed to generate PDF. Please try again.')
        }
    }

    const handleStartOver = () => {
        setStep('input')
        setGeneratedLetter('')
    }

    return (
        <div className="min-h-screen bg-zinc-950">
            {/* Mobile Header */}
            <header className="lg:hidden fixed top-0 left-0 right-0 z-50 bg-zinc-900/95 backdrop-blur-xl border-b border-zinc-800">
                <div className="flex items-center justify-between px-4 h-14">
                    <button onClick={() => setSidebarOpen(true)} className="p-2 -ml-2 text-zinc-400 hover:text-white">
                        <Menu className="w-5 h-5" />
                    </button>
                    <div className="flex items-center gap-2">
                        <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center">
                            <Zap className="w-4 h-4 text-white" />
                        </div>
                        <span className="font-semibold text-white">ApplyOps</span>
                    </div>
                    <div className="w-8 h-8 rounded-full bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center text-white text-sm font-medium">
                        {user?.name?.charAt(0) || 'U'}
                    </div>
                </div>
            </header>

            {/* Mobile Sidebar */}
            {sidebarOpen && (
                <div className="lg:hidden fixed inset-0 z-50">
                    <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={() => setSidebarOpen(false)} />
                    <aside className="absolute left-0 top-0 bottom-0 w-72 bg-zinc-900 border-r border-zinc-800 animate-slide-in-left">
                        <SidebarContent user={user} logout={logout} navItems={navItems} onClose={() => setSidebarOpen(false)} />
                    </aside>
                </div>
            )}

            {/* Desktop Sidebar */}
            <aside className="hidden lg:flex fixed left-0 top-0 bottom-0 w-64 bg-zinc-900/80 backdrop-blur-xl border-r border-zinc-800 flex-col">
                <SidebarContent user={user} logout={logout} navItems={navItems} />
            </aside>

            {/* Main Content */}
            <main className="lg:ml-64 pt-14 lg:pt-0 min-h-screen">
                <div className="p-4 sm:p-6 lg:p-8 max-w-4xl mx-auto">
                    {/* Header */}
                    <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-8">
                        <div>
                            <h1 className="text-2xl font-bold text-white flex items-center gap-2">
                                <Sparkles className="w-6 h-6 text-violet-400" />
                                AI Cover Letter Generator
                            </h1>
                            <p className="text-zinc-400 text-sm mt-1">Generate personalized cover letters in seconds</p>
                        </div>
                    </div>

                    {/* Step Indicator */}
                    <div className="flex items-center gap-2 mb-8">
                        {['Input', 'Generate', 'Result'].map((label, i) => (
                            <div key={label} className="flex items-center gap-2">
                                <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium transition-colors ${(step === 'input' && i === 0) || (step === 'generating' && i === 1) || (step === 'result' && i === 2)
                                    ? 'bg-violet-500 text-white'
                                    : i < (['input', 'generating', 'result'].indexOf(step))
                                        ? 'bg-emerald-500 text-white'
                                        : 'bg-zinc-800 text-zinc-500'
                                    }`}>
                                    {i < (['input', 'generating', 'result'].indexOf(step)) ? (
                                        <Check className="w-4 h-4" />
                                    ) : (
                                        i + 1
                                    )}
                                </div>
                                <span className={`text-sm hidden sm:block ${(step === 'input' && i === 0) || (step === 'generating' && i === 1) || (step === 'result' && i === 2)
                                    ? 'text-white font-medium'
                                    : 'text-zinc-500'
                                    }`}>{label}</span>
                                {i < 2 && <div className="w-8 h-px bg-zinc-800" />}
                            </div>
                        ))}
                    </div>

                    {/* Input Step */}
                    {step === 'input' && (
                        <div className="space-y-6">
                            {/* Job Details */}
                            <Card>
                                <CardHeader>
                                    <CardTitle className="text-base flex items-center gap-2">
                                        <Building2 className="w-5 h-5 text-violet-400" />
                                        Job Details
                                    </CardTitle>
                                    <CardDescription>Tell us about the position you're applying for</CardDescription>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <div className="grid sm:grid-cols-2 gap-4">
                                        <div className="space-y-2">
                                            <Label htmlFor="company">Company Name</Label>
                                            <Input
                                                id="company"
                                                placeholder="e.g., Google"
                                                value={companyName}
                                                onChange={(e) => setCompanyName(e.target.value)}
                                            />
                                        </div>
                                        <div className="space-y-2">
                                            <Label htmlFor="role">Role Title</Label>
                                            <Input
                                                id="role"
                                                placeholder="e.g., Senior Software Engineer"
                                                value={roleName}
                                                onChange={(e) => setRoleName(e.target.value)}
                                            />
                                        </div>
                                    </div>
                                    <div className="space-y-2">
                                        <Label htmlFor="description">Job Description (optional)</Label>
                                        <textarea
                                            id="description"
                                            placeholder="Paste the job description here for a more tailored cover letter..."
                                            value={jobDescription}
                                            onChange={(e) => setJobDescription(e.target.value)}
                                            className="flex min-h-32 w-full rounded-xl border border-zinc-800 bg-zinc-900/50 px-4 py-3 text-sm text-zinc-100 placeholder:text-zinc-500 focus:outline-none focus:ring-2 focus:ring-violet-500/50 focus:border-violet-500 resize-none"
                                        />
                                    </div>
                                </CardContent>
                            </Card>

                            {/* Tone Selection */}
                            <Card>
                                <CardHeader>
                                    <CardTitle className="text-base flex items-center gap-2">
                                        <Wand2 className="w-5 h-5 text-violet-400" />
                                        Writing Tone
                                    </CardTitle>
                                    <CardDescription>Choose the style that matches the company culture</CardDescription>
                                </CardHeader>
                                <CardContent>
                                    <div className="grid sm:grid-cols-2 gap-3">
                                        {toneOptions.map((tone) => (
                                            <button
                                                key={tone.id}
                                                onClick={() => setSelectedTone(tone.id)}
                                                className={`p-4 rounded-xl border text-left transition-all ${selectedTone === tone.id
                                                    ? 'border-violet-500 bg-violet-500/10'
                                                    : 'border-zinc-800 hover:border-zinc-700 bg-zinc-900/50'
                                                    }`}
                                            >
                                                <div className="flex items-center gap-3">
                                                    <span className="text-2xl">{tone.icon}</span>
                                                    <div>
                                                        <p className={`font-medium ${selectedTone === tone.id ? 'text-violet-400' : 'text-white'}`}>
                                                            {tone.label}
                                                        </p>
                                                        <p className="text-xs text-zinc-500">{tone.description}</p>
                                                    </div>
                                                </div>
                                            </button>
                                        ))}
                                    </div>
                                </CardContent>
                            </Card>

                            {/* Generate Button */}
                            <Button
                                variant="gradient"
                                size="lg"
                                className="w-full"
                                onClick={handleGenerate}
                                disabled={!companyName || !roleName}
                            >
                                <Sparkles className="w-5 h-5 mr-2" />
                                Generate Cover Letter
                            </Button>
                        </div>
                    )}

                    {/* Generating Step */}
                    {step === 'generating' && (
                        <Card>
                            <CardContent className="py-20">
                                <div className="text-center">
                                    <div className="w-16 h-16 rounded-2xl bg-violet-500/10 flex items-center justify-center mx-auto mb-6">
                                        <RefreshCw className="w-8 h-8 text-violet-400 animate-spin" />
                                    </div>
                                    <h3 className="text-xl font-semibold text-white mb-2">Crafting your cover letter...</h3>
                                    <p className="text-zinc-400 text-sm">Our AI is analyzing the job details and generating a personalized letter</p>
                                </div>
                            </CardContent>
                        </Card>
                    )}

                    {/* Result Step */}
                    {step === 'result' && (
                        <div className="space-y-6">
                            <Card>
                                <CardHeader>
                                    <div className="flex items-center justify-between">
                                        <div>
                                            <CardTitle className="text-base">Generated Cover Letter</CardTitle>
                                            <CardDescription>For {roleName} at {companyName}</CardDescription>
                                        </div>
                                        <Badge variant="success">
                                            <Check className="w-3 h-3 mr-1" />
                                            AI Generated
                                        </Badge>
                                    </div>
                                </CardHeader>
                                <CardContent>
                                    <div id="cover-letter-preview" className="bg-white text-zinc-900 border border-zinc-200 rounded-lg p-10 mb-6 shadow-sm min-h-[500px]">
                                        <pre className="whitespace-pre-wrap text-base font-serif leading-relaxed">
                                            {generatedLetter}
                                        </pre>
                                    </div>

                                    <div className="flex flex-wrap gap-3">
                                        <Button variant="gradient" onClick={handleCopy}>
                                            {copied ? <Check className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
                                            {copied ? 'Copied!' : 'Copy to Clipboard'}
                                        </Button>
                                        <Button variant="outline" onClick={handleDownloadPDF}>
                                            <Download className="w-4 h-4 mr-2" />
                                            Download as PDF
                                        </Button>
                                        <Button variant="ghost" onClick={handleGenerate}>
                                            <RefreshCw className="w-4 h-4 mr-2" />
                                            Regenerate
                                        </Button>
                                    </div>
                                </CardContent>
                            </Card>

                            <Button variant="outline" className="w-full" onClick={handleStartOver}>
                                Start New Cover Letter
                            </Button>
                        </div>
                    )}
                </div>
            </main>
        </div>
    )
}

// Sidebar Component
function SidebarContent({
    user,
    logout,
    navItems,
    onClose
}: {
    user: User | null
    logout: () => void
    navItems: { icon: typeof Briefcase; label: string; href: string; active?: boolean }[]
    onClose?: () => void
}) {
    return (
        <div className="flex flex-col h-full p-4">
            <div className="flex items-center justify-between mb-8">
                <Link to="/" className="flex items-center gap-2.5">
                    <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center shadow-lg shadow-violet-500/25">
                        <Zap className="w-5 h-5 text-white" />
                    </div>
                    <span className="text-lg font-semibold text-white">ApplyOps</span>
                </Link>
                {onClose && (
                    <button onClick={onClose} className="lg:hidden p-2 text-zinc-500 hover:text-white">
                        <X className="w-5 h-5" />
                    </button>
                )}
            </div>

            <nav className="flex-1 space-y-1">
                {navItems.map((item) => (
                    <Link
                        key={item.label}
                        to={item.href}
                        onClick={onClose}
                        className={`flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-colors ${item.active
                            ? 'bg-violet-500/10 text-violet-400'
                            : 'text-zinc-400 hover:bg-zinc-800 hover:text-white'
                            }`}
                    >
                        <item.icon className="w-5 h-5" />
                        {item.label}
                    </Link>
                ))}
            </nav>

            <div className="mb-4 p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50">
                <div className="flex items-center gap-2 mb-3">
                    <Mail className="w-4 h-4 text-zinc-500" />
                    <span className="text-sm font-medium text-zinc-300">Gmail Sync</span>
                </div>
                {user?.gmailConnected ? (
                    <div className="flex items-center gap-2 text-emerald-400 text-xs">
                        <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                        Connected & tracking
                    </div>
                ) : (
                    <Button size="sm" variant="outline" className="w-full text-xs h-8" onClick={() => authApi.connectGmail()}>
                        Connect Gmail
                    </Button>
                )}
            </div>

            <div className="border-t border-zinc-800 pt-4">
                <div className="flex items-center gap-3 mb-3 px-1">
                    <div className="w-9 h-9 rounded-full bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center text-white text-sm font-medium">
                        {user?.name?.charAt(0) || 'U'}
                    </div>
                    <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-white truncate">{user?.name || 'User'}</p>
                        <p className="text-xs text-zinc-500 truncate">{user?.email || 'user@example.com'}</p>
                    </div>
                </div>
                <Button variant="ghost" size="sm" className="w-full justify-start text-zinc-500 h-9" onClick={logout}>
                    <LogOut className="w-4 h-4 mr-2" />
                    Sign out
                </Button>
            </div>
        </div>
    )
}
